workflows:
  react-native-workflow:
    name: React Native CI/CD
    max_build_duration: 60
    environment:
      node: latest
      xcode: latest
      vars:
        APP_NAME: "MyApp"
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Run tests
        script: |
          npm test
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleRelease
      - name: Build iOS
        script: |
          cd ios
          xcodebuild -workspace MyApp.xcworkspace -scheme MyApp -configuration Release -sdk iphoneos
    artifacts:
      - android/app/build/outputs/**/*.apk
      - ios/build/**/*.app